name: First Workflow

on: push

jobs:
  example-job:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Message
        run: echo "My first GitHub Actions workflow"
